name: CST-GL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - matplotlib=3.1.1
  - numpy=1.17.4
  - pandas=0.25.3
  - scipy=1.4.1
  - pytorch=1.7.0
  - scikit-learn=0.23.2